foreground #e0e4db
background #10140f
cursor #9fd49c

selection_foreground #253424
selection_background #b9ccb4

# Black
color0 #1c211b
color8 #272b25

# Red
color1 #ffb4ab
color9 #ffb4ab

# Green
color2 #9fd49c
color10 #9fd49c

# Yellow
color3 #a1ced5
color11 #a1ced5

# Blue
color4 #b9ccb4
color12 #b9ccb4

# Magenta
color5 #a1ced5
color13 #a1ced5

# Cyan
color6 #b9ccb4
color14 #b9ccb4

# White
color7 #e0e4db
color15 #c2c9bd
