[Appearance]
color_scheme_path=/home/tony/.config/qt5ct/colors/caelestia.colors
custom_palette=true
icon_theme=Papirus-Dark
standard_dialogs=default
style=Darkly

[Fonts]
fixed="Monospace,12,-1,5,50,0,0,0,0,0"
general="Sans Serif,12,-1,5,50,0,0,0,0,0"

[SettingsWindow]
geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\0\0\0\0\0\0\0\0\x3\x84\0\0\x4\r\0\0\0\0\0\0\0\0\0\0\x3\x89\0\0\x3\xff\0\0\0\0\x2\0\0\0\a\x80\0\0\0\0\0\0\0\0\0\0\x3\x84\0\0\x4\r)
