$background = 0f0d0b
$onBackground = e8e2dc
$surface = 0f0d0b
$surfaceDim = 0f0d0b
$surfaceBright = 2e2a24
$surfaceContainerLowest = 000000
$surfaceContainerLow = 14120f
$surfaceContainer = 1a1815
$surfaceContainerHigh = 201d1a
$surfaceContainerHighest = 27231f
$onSurface = e8e2dc
$surfaceVariant = 27231f
$onSurfaceVariant = b7a998
$outline = 7f7465
$outlineVariant = 504639
$inverseSurface = faf9f8
$inverseOnSurface = 5b544c
$shadow = 000000
$scrim = 000000
$surfaceTint = c0b9af
$primary = dfbf90
$primaryDim = d9b37b
$onPrimary = 4e3916
$primaryContainer = 694d20
$onPrimaryContainer = eddbc3
$inversePrimary = 775a2b
$primaryFixed = e9d3b2
$primaryFixedDim = e2c69d
$onPrimaryFixed = 463414
$onPrimaryFixedVariant = 6f5325
$secondary = dcc3a1
$secondaryDim = ceb594
$onSecondary = 4e3d24
$secondaryContainer = 493920
$onSecondaryContainer = d4bc9a
$secondaryFixed = eeddc6
$secondaryFixedDim = e8d1b0
$onSecondaryFixed = 4d3d23
$onSecondaryFixedVariant = 6b583d
$tertiary = e9c5b4
$tertiaryDim = e3b49d
$onTertiary = 653820
$tertiaryContainer = e3b49d
$onTertiaryContainer = 58301a
$tertiaryFixed = e3b49d
$tertiaryFixedDim = dda488
$onTertiaryFixed = 351e10
$onTertiaryFixedVariant = 65381f
$error = d88b79
$errorDim = c05138
$onError = 351410
$errorContainer = 6f3020
$onErrorContainer = e3ac9e
$primaryPaletteKeyColor = 927241
$secondaryPaletteKeyColor = 897457
$tertiaryPaletteKeyColor = a16a4e
$neutralPaletteKeyColor = 7e766d
$neutralVariantPaletteKeyColor = 817566
$errorPaletteKeyColor = c45439
$primary_paletteKeyColor = 927241
$secondary_paletteKeyColor = 897457
$tertiary_paletteKeyColor = a16a4e
$neutral_paletteKeyColor = 7e766d
$neutral_variant_paletteKeyColor = 817566
$term0 = 343434
$term1 = cd6830
$term2 = d7c553
$term3 = f2dfc6
$term4 = 7cb69f
$term5 = e7989e
$term6 = b5d38a
$term7 = e7d6bf
$term8 = b0a090
$term9 = df9576
$term10 = d9cb5b
$term11 = f9f1e8
$term12 = aec8ac
$term13 = eeb8b5
$term14 = cce48e
$term15 = ffffff
$rosewater = fbf0ec
$flamingo = f6dfda
$pink = f6dae0
$mauve = ecb0df
$red = eaaaa7
$maroon = ecb5ae
$peach = eac4a6
$yellow = f7eddd
$green = c9e799
$teal = b1edc3
$sky = 9be7d5
$sapphire = 70d7da
$blue = c8c2f1
$lavender = dfccf3
$klink = 267885
$klinkSelection = 267885
$kvisited = c45d97
$kvisitedSelection = c45d97
$knegative = cd6951
$knegativeSelection = cd6951
$kneutral = cd8e51
$kneutralSelection = cc8d50
$kpositive = 7bba46
$kpositiveSelection = 7aba47
$text = e8e2dc
$subtext1 = b7a998
$subtext0 = 7f7465
$overlay2 = 6f6558
$overlay1 = 5f564a
$overlay0 = 4f483e
$surface2 = 3f3a32
$surface1 = 302c26
$surface0 = 1f1d19
$base = 0f0d0b
$mantle = 0f0d0b
$crust = 0e0d0b
$success = B5CCBA
$onSuccess = 213528
$successContainer = 374B3E
$onSuccessContainer = D1E9D6
