#!/usr/bin/env python3
"""Generate a wallpaper-derived theme for Cider and live-inject it over CDP.

Reads the caelestia colour scheme (from $SCHEME_COLOURS when invoked by the
post-theme-hook, else from scheme.json), maps the Material You palette onto the
CSS custom properties Cider's UI honours, writes the CSS to the caelestia theme
dir, and pushes it into a running Cider via the Chrome DevTools Protocol so the
window re-colours live without a restart.

If Cider isn't running / the debug port is closed, the CSS file is still written
and the script exits 0 (so it never breaks the rest of the hook).
"""

import json
import os
import sys
import urllib.request

PORT = 9223
STYLE_ID = "caelestia-cider"
SCHEME_JSON = os.path.expanduser("~/.local/state/caelestia/scheme.json")
OUT_CSS = os.path.expanduser("~/.local/state/caelestia/theme/cider.css")


def load_colours() -> dict:
    env = os.environ.get("SCHEME_COLOURS")
    if env:
        return json.loads(env)
    with open(SCHEME_JSON) as f:
        return json.load(f)["colours"]


def rgb(h: str) -> str:
    h = h.lstrip("#")
    return f"{int(h[0:2],16)}, {int(h[2:4],16)}, {int(h[4:6],16)}"


def build_vars(c: dict) -> dict:
    """Return the full {--cssVar: value} map (hex colours + -rgb companions)."""
    def g(key: str, fallback: str = "ffffff") -> str:
        return c.get(key, fallback)

    # Material You -> Cider vocabulary. Names verified against Cider's own
    # themes (themes/12 Catppuccin) which prove these vars theme the UI.
    primary = g("primary")
    on_primary = g("onPrimary")
    on_surface = g("onSurface")
    on_surface_var = g("onSurfaceVariant")

    pairs = {
        # backgrounds (dark -> darker)
        "base": g("surface"),
        "mantle": g("surfaceContainerLow"),
        "crust": g("surfaceContainerLowest"),
        # surfaces / panels
        "surface0": g("surfaceContainer"),
        "tracklistAltRowColor": g("surfaceContainerHigh"),
        "selection-bg": g("secondaryContainer"),
        "vibrantDivider": g("outlineVariant"),
        # text / system greys (high -> low emphasis)
        "text": on_surface,
        "textDefault": on_surface,
        "systemPrimary": on_surface,
        "subtext1": on_surface_var,
        "systemSecondary": on_surface_var,
        "subtext0": g("outline"),
        "systemTertiary": g("outline"),
        "overlay1": g("outline"),
        "overlay0": g("outlineVariant"),
        "systemQuaternary": g("outlineVariant"),
        "systemQuinary": g("outlineVariant"),
        # accent / key colours
        "accent": primary,
        "keyColor": primary,
        "musicKeyColor": primary,
        "q-primary": primary,
        "q-info": primary,
        "progressColor": primary,
        "gradientColor": primary,
        "defaultColor": primary,
        "eq-bars-bg-color": primary,
        "buttonColor": primary,
        "buttonTextColor": on_primary,
        "red": g("error"),
    }
    # rgb companions used by Cider's rgba(var(--x-rgb), a) rules
    rgb_keys = ["keyColor", "musicKeyColor", "accent", "buttonColor"]

    out = {f"--{k}": f"#{v}" for k, v in pairs.items()}
    out.update({f"--{k}-rgb": rgb(pairs[k]) for k in rgb_keys})
    return out


def build_css(vars_: dict) -> str:
    # No @property/transition: registering these conflicts with Cider's own
    # @property+transition on the same vars and freezes them. Cider already
    # declares ~1s transitions on its colour vars, so plain values cross-fade
    # smoothly on their own.
    body = "\n".join(f"  {k}: {v};" for k, v in vars_.items())
    # Target :root and the dark-mode body class (Cider scopes some defaults to
    # body.body--dark, which is more specific than :root).
    return (
        "/* Caelestia Cider theme - generated by cider-theme.py */\n"
        f":root, body, body.body--dark, body.body--light {{\n{body}\n}}\n"
    )


def write_file(css: str) -> None:
    os.makedirs(os.path.dirname(OUT_CSS), exist_ok=True)
    with open(OUT_CSS, "w") as f:
        f.write(css)


def inject(css: str, vars_: dict) -> bool:
    """Apply the theme to the running Cider renderer via CDP: upsert a <style>
    tag (for @property/transition) and set every var inline with !important on
    the root element (beats Cider's own inline accent from customAccentColor).
    Returns True on success, False if Cider/the debug port isn't reachable."""
    try:
        import websocket  # websocket-client
    except ImportError:
        print("websocket-client not installed; skipping live inject", file=sys.stderr)
        return False
    try:
        with urllib.request.urlopen(f"http://127.0.0.1:{PORT}/json", timeout=2) as r:
            targets = json.load(r)
    except OSError:
        return False  # port closed / Cider not running

    pages = [t for t in targets if t.get("type") == "page"
             and not t.get("url", "").startswith("devtools://")]
    if not pages:
        return False
    ws_url = pages[0]["webSocketDebuggerUrl"]

    expr = (
        "(function(){var css=%s;var id=%s;var v=%s;"
        "var s=document.getElementById(id);"
        "if(!s){s=document.createElement('style');s.id=id;"
        "(document.head||document.documentElement).appendChild(s);}"
        "s.textContent=css;"
        # Cider sets some vars (e.g. --keyColor from customAccentColor) inline
        # on <body>; a child's own declaration beats an inherited !important,
        # so we override on <html> AND <body>.
        "[document.documentElement,document.body].forEach(function(r){"
        "if(r){for(var k in v){r.style.setProperty(k,v[k],'important');}}});})()"
    ) % (json.dumps(css), json.dumps(STYLE_ID), json.dumps(vars_))

    try:
        # suppress_origin: Electron/Chromium rejects CDP WebSocket handshakes
        # that carry a browser Origin header unless it's allow-listed; CLI
        # clients with no Origin are trusted.
        ws = websocket.create_connection(ws_url, timeout=5, suppress_origin=True)
        ws.send(json.dumps({"id": 1, "method": "Runtime.evaluate",
                            "params": {"expression": expr}}))
        ws.recv()
        ws.close()
    except Exception as e:  # noqa: BLE001 - never break the hook
        print(f"CDP inject failed: {e}", file=sys.stderr)
        return False
    return True


def main() -> int:
    vars_ = build_vars(load_colours())
    css = build_css(vars_)
    write_file(css)
    inject(css, vars_)  # best-effort; failure is non-fatal
    return 0


if __name__ == "__main__":
    sys.exit(main())
