input {
    follow_mouse = 2
}

input {
    numlock_by_default = true
}

exec-once = clipse -listen
exec-once = hyprsunset

bind = Super, N, exec, ~/.local/bin/night-mode.sh
# bind = Super+Shift, E, exec, bash -c "conda run -n mtp --live-stream python ~/iitkgp-erp-login-pypi/examples/open_erp.py"
bind = Super+Shift, T, exec, quickshell -c QuickSnip -n
