$kbMoveWinToWs = Super+Shift
$volumeStep = 5
$touchpadScrollFactor = 1.5

$cursorTheme = macOS

$workspaceGaps = 10
$windowGapsIn = 10
$windowGapsOut = 15
$singleWindowGapsOut = 25

$kbNextWs = Ctrl+Super, j
$kbPrevWs = Ctrl+Super, k
