#!/bin/sh
# Reload apps that don't watch their config files for changes.

# kitty: SIGUSR1 triggers a live config reload
pkill -SIGUSR1 kitty 2>/dev/null

# KDE apps: apply the generated Plasma color scheme.
# Bounce through BreezeLight first — plasma-apply-colorscheme skips the D-Bus
# notification if the scheme name is already active, so this forces a real change
# event that causes Dolphin, QBittorrent, etc. to repaint.
#
# plasma-apply-colorscheme BreezeLight >/dev/null 2>&1
plasma-apply-colorscheme CaelestiaTheme 2>/dev/null

# Neovim: signal each running instance via its server socket.
# Instances started without --listen won't have a socket and are silently skipped.
for socket in /run/user/"$(id -u)"/nvim.*.0 /tmp/nvim.*/nvim.*.0; do
  [ -S "$socket" ] && nvim --server "$socket" \
    --remote-send ':colorscheme caelestia<CR>' 2>/dev/null
done

# Sioyek: fix visual_mark_color (sioyek uses space-separated floats, not hex).
# The template writes a static placeholder; overwrite it with the real value.
_sf="${HOME}/.local/state/caelestia/theme/sioyek.config"
if [ -f "$_sf" ] && [ -n "$SCHEME_COLOURS" ]; then
  _mc=$(python3 -c "
import json, os
h = json.loads(os.environ['SCHEME_COLOURS']).get('tertiary', 'afceb5')
r, g, b = int(h[0:2], 16)/255, int(h[2:4], 16)/255, int(h[4:6], 16)/255
print(f'{r:.8f} {g:.8f} {b:.8f} 0.2')
")
  sed -i "s/^visual_mark_color .*/visual_mark_color $_mc/" "$_sf"
fi

# Zen Browser: translate Caelestia colors and update Color Boost
if [ -x "${HOME}/.config/zen-boosts/apply_zen_boost.py" ]; then
  "${HOME}/.config/zen-boosts/apply_zen_boost.py"
fi

# Kvantum: patch the SVG to replace accent blues with caelestia colors,
# then symlink the pair into ~/.config/Kvantum/Caelestia/ so Qt apps see it.
_kvtheme="$HOME/.local/state/caelestia/theme"
_kvconfig_svg="$HOME/.config/Kvantum/WhiteSur/WhiteSurDark.svg"
_kvout="$HOME/.config/Kvantum/Caelestia"
if [ -f "$_kvconfig_svg" ] && [ -n "$SCHEME_COLOURS" ]; then
  python3 -c "
import json, os

c = json.loads(os.environ['SCHEME_COLOURS'])
def g(k, fb):
    v = c.get(k, fb)
    return v if v else fb

pri     = g('primary',            'a0b4f8')
pri_dim = g('primaryFixedDim',    'baa57d')  # lighter than primary
pri_med = g('inversePrimary',     '775a2b')  # darker, richer accent
pri_drk = g('primaryContainer',   '694d20')  # darkest accent (pressed)
sec      = g('secondary',          'b0a08a')
ter      = g('tertiary',           'd4b0a0')

svg = open(os.path.expanduser('$_kvconfig_svg')).read()

# Each original blue mapped to a caelestia equivalent, preserving
# the relative light/dark hierarchy of the original.
# Gradient pairs keep the dark->light direction.
replacements = {
    # --- highlight-level (lightest blue) -> primary ---
    '#5887fc': pri,       # hightlight gradient (selected items)
    '#5294e2': pri,       # dial-handle, menubaritem-pressed
    '#0078f0': pri,       # path7945
    '#67676a': pri,       # lineedit-focused border

    # --- medium accent (medium blue) -> dim/fixed/med ---
    '#31a7e8': pri_dim,   # mdi-restore-normal (window button)
    '#3daee9': pri_dim,   # common-normal, group-normal (elem bg)
    '#315bef': pri_med,   # slider-toggled, combo-toggled/focused
    '#6179df': sec,        # rect6589 (secondary accent)
    '#8591e3': ter,        # rect6745, rect6791 (tertiary accent)
    '#3176bf': sec,        # tab-tear (drag indicator)

    # --- darkest accent (darkest blue) -> primaryContainer ---
    '#144fb8': pri_drk,   # button-pressed

    # --- gradient pairs (dark->light) ---
    '#3458c0': pri_drk,   # dark_checked_bg  start
    '#3d67e3': pri_med,   # dark_checked_bg  end
    '#1759ce': pri_drk,   # toggled button   start
    '#1a62e7': pri_med,   # toggled button   end
    '#245fc4': pri_drk,   # gradient1933     start
    '#286adc': pri_med,   # gradient1933     end
}

for old, new in replacements.items():
    svg = svg.replace(old,      f'#{new}')
    svg = svg.replace(old.upper(), f'#{new}')

open(os.path.expanduser('$_kvtheme/Caelestia.svg'), 'w').write(svg)
"
  mkdir -p "$_kvout"
  ln -sf "$_kvtheme/Caelestia.kvconfig" "$_kvout/Caelestia.kvconfig"
  ln -sf "$_kvtheme/Caelestia.svg" "$_kvout/Caelestia.svg"
fi

# Generate Lua scheme file for Hyprland Lua configs.
# caelestia-cli only writes current.conf (hyprlang), but the Lua config
# requires current.lua.  SCHEME_COLOURS provides all colours as JSON.
if [ -n "$SCHEME_COLOURS" ]; then
  python3 -c "
import json, os
colours = json.loads(os.environ['SCHEME_COLOURS'])
path = os.path.expanduser('~/.config/hypr/scheme/current.lua')
lines = ['-- Color scheme - generated by Caelestia',
         '-- This is the Lua port of current.conf',
         'return {']
for k, v in colours.items():
    lines.append(f'    {k} = \"{v}\",')
lines.append('}')
with open(path, 'w') as f:
    f.write('\n'.join(lines) + '\n')
" 2>/dev/null
fi
