$hypr = ~/.config/hypr
$hl = $hypr/hyprland
$cConf = ~/.config/caelestia

# Variables (colours + other vars)
exec = cp -L --no-preserve=mode --update=none $hypr/scheme/default.conf $hypr/scheme/current.conf
source = $hypr/scheme/current.conf
source = $hypr/variables.conf

# User variables
exec = mkdir -p $cConf && touch -a $cConf/hypr-vars.conf
source = $cConf/hypr-vars.conf

# Default monitor conf
monitor = , preferred, auto, 1
# source = $hypr/monitors.conf
# Configs
source = $hl/env.conf
source = $hl/general.conf
source = $hl/input.conf
source = $hl/misc.conf
source = $hl/animations.conf
source = $hl/decoration.conf
source = $hl/group.conf
source = $hl/execs.conf
source = $hl/rules.conf
source = $hl/gestures.conf
source = $hl/keybinds.conf

# User configs
exec = mkdir -p $cConf && touch -a $cConf/hypr-user.conf
source = $cConf/hypr-user.conf


# plugin {
#   hyprfocus {
#     enabled = yes
#     animate_floating = yes
#     animate_workspacechange = yes
#     focus_animation = flash
#       # Beziers for focus animations
#     bezier = bezIn, 0.5, 0.0, 1.0, 0.5
#     bezier = bezOut, 0.0, 0.5, 0.5, 1.0
#     bezier = overshot, 0.05, 0.9, 0.1, 1.05
#     bezier = smoothOut, 0.36, 0, 0.66, -0.56
#     bezier = smoothIn, 0.25, 1, 0.5, 1
#     bezier = realsmooth, 0.28, 0.29, 0.69, 1.08
#     bezier = easeInOutBack, 0.68, -0.6, 0.32, 1.6
#       # Flash settings
#     flash {
#       flash_opacity = 0.5
#       in_bezier = bezIn
#       in_speed = 0.5
#       out_bezier = bezOut
#       out_speed = 1.5
#     }
#       # Shrink settings
#     shrink {
#       shrink_percentage = 0.97
#       in_bezier = easeInOutBack
#       in_speed = 3.5
#       out_bezier = easeInOutBack
#       out_speed = 3
#     }
#   }
#    hyprtasking {
#     layout = grid
#
#     gap_size = 20
#     bg_color = 0x31393f
#     border_size = 4
#     exit_on_hovered = false
#     warp_on_move_window = 1
#     close_overview_on_reload = true
#
#     drag_button = 0x110 # left mouse button
#     select_button = 0x111 # right mouse button
#     # for other mouse buttons see <linux/input-event-codes.h>
#
#     gestures {
#       enabled = false
#       move_fingers = 3
#       move_distance = 500
#       open_fingers = 4
#       open_distance = 300
#       open_positive = true
#     }
#
#     grid {
#       rows = 3
#       cols = 3
#       loop = false
#       layers = 2
#       loop_layers = true
#       gaps_use_aspect_ratio = true
#     }
#
#     linear {
#       top = false
#       height = 400
#       scroll_speed = 1.0
#       blur = false
#     }
#   }
#
# }

