return {
  mode = "{{ mode }}",
  palette = {
    -- Backgrounds
    bg0 = "#{{ surface.hex }}",
    bg1 = "#{{ surfaceContainerLow.hex }}",
    bg2 = "#{{ surfaceContainer.hex }}",
    bg3 = "#{{ surfaceContainerHigh.hex }}",
    bg4 = "#{{ surfaceContainerHighest.hex }}",
    
    -- Foregrounds
    fg0 = "#{{ onSurface.hex }}",
    fg1 = "#{{ onSurfaceVariant.hex }}",
    fg2 = "#{{ outline.hex }}",
    fg3 = "#{{ outlineVariant.hex }}",
    fg4 = "#{{ outlineVariant.hex }}",
    
    -- Semantic Colors (Hue-based "Rainbow")
    red    = "#{{ red.hex }}",
    green  = "#{{ green.hex }}",
    yellow = "#{{ yellow.hex }}",
    blue   = "#{{ blue.hex }}",
    purple = "#{{ mauve.hex }}",
    aqua   = "#{{ sky.hex }}",
    orange = "#{{ peach.hex }}",
    pink   = "#{{ pink.hex }}",
    teal   = "#{{ teal.hex }}",
    
    -- M3 Semantic Roles
    primary   = "#{{ primary.hex }}",
    secondary = "#{{ secondary.hex }}",
    tertiary  = "#{{ tertiary.hex }}",
    error     = "#{{ error.hex }}",
    
    -- Containers & On-Colors
    primaryContainer   = "#{{ primaryContainer.hex }}",
    onPrimaryContainer = "#{{ onPrimaryContainer.hex }}",
    secondaryContainer = "#{{ secondaryContainer.hex }}",
    onSecondaryContainer = "#{{ onSecondaryContainer.hex }}",
    tertiaryContainer  = "#{{ tertiaryContainer.hex }}",
    onTertiaryContainer = "#{{ onTertiaryContainer.hex }}",
    errorContainer     = "#{{ errorContainer.hex }}",
    onErrorContainer   = "#{{ onErrorContainer.hex }}",
  },
  highlights = {
    -- 1. Base Syntax (Fixed visibility for Operators/Delimiters)
    Normal = { fg = "#{{ onSurface.hex }}", bg = "#{{ surface.hex }}" },
    Comment = { fg = "#{{ onSurfaceVariant.hex }}", italic = true },
    Constant = { fg = "#{{ mauve.hex }}" },
    String = { fg = "#{{ green.hex }}" },
    Character = { fg = "#{{ green.hex }}" },
    Number = { fg = "#{{ mauve.hex }}" },
    Boolean = { fg = "#{{ peach.hex }}" },
    Float = { fg = "#{{ mauve.hex }}" },
    Identifier = { fg = "#{{ onSurface.hex }}" },
    Function = { fg = "#{{ secondary.hex }}" },
    Statement = { fg = "#{{ primary.hex }}" },
    Conditional = { fg = "#{{ primary.hex }}" },
    Repeat = { fg = "#{{ primary.hex }}" },
    Label = { fg = "#{{ primary.hex }}" },
    
    -- FIX: Operators and Delimiters use fg1 (onSurfaceVariant) for better visibility than outlineVariant
    Operator = { fg = "#{{ onSurfaceVariant.hex }}" },
    Delimiter = { fg = "#{{ onSurfaceVariant.hex }}" },
    
    Keyword = { fg = "#{{ primary.hex }}" },
    Exception = { fg = "#{{ primary.hex }}" },
    PreProc = { fg = "#{{ pink.hex }}" },
    Include = { fg = "#{{ pink.hex }}" },
    Define = { fg = "#{{ pink.hex }}" },
    Macro = { fg = "#{{ pink.hex }}" },
    PreCondit = { fg = "#{{ pink.hex }}" },
    Type = { fg = "#{{ tertiary.hex }}" },
    StorageClass = { fg = "#{{ primary.hex }}" },
    Structure = { fg = "#{{ tertiary.hex }}" },
    Typedef = { fg = "#{{ tertiary.hex }}" },
    Special = { fg = "#{{ peach.hex }}" },
    SpecialChar = { fg = "#{{ pink.hex }}" },
    Tag = { fg = "#{{ secondary.hex }}" },
    SpecialComment = { fg = "#{{ onSurfaceVariant.hex }}", italic = true },
    Debug = { fg = "#{{ error.hex }}" },
    Underlined = { underline = true },
    Ignore = { fg = "#{{ outline.hex }}" },
    Error = { fg = "#{{ error.hex }}", bold = true },
    Todo = { fg = "#{{ surface.hex }}", bg = "#{{ secondary.hex }}", bold = true },

    -- 2. Treesitter (Detailed Mapping)
    ["@comment"] = { link = "Comment" },
    ["@none"] = { fg = "NONE", bg = "NONE" },
    ["@preproc"] = { link = "PreProc" },
    ["@define"] = { link = "Define" },
    ["@operator"] = { link = "Operator" },
    ["@punctuation.delimiter"] = { link = "Delimiter" },
    ["@punctuation.bracket"] = { link = "Delimiter" },
    ["@punctuation.special"] = { link = "Delimiter" },
    ["@string"] = { link = "String" },
    ["@string.regex"] = { fg = "#{{ pink.hex }}" },
    ["@string.escape"] = { fg = "#{{ pink.hex }}" },
    ["@string.special"] = { fg = "#{{ pink.hex }}" },
    ["@character"] = { link = "Character" },
    ["@boolean"] = { link = "Boolean" },
    ["@number"] = { link = "Number" },
    ["@float"] = { link = "Float" },
    ["@function"] = { link = "Function" },
    ["@function.builtin"] = { fg = "#{{ secondary.hex }}", italic = true },
    ["@function.call"] = { link = "Function" },
    ["@function.macro"] = { link = "Macro" },
    ["@method"] = { link = "Function" },
    ["@method.call"] = { link = "Function" },
    ["@constructor"] = { fg = "#{{ tertiary.hex }}" },
    ["@parameter"] = { fg = "#{{ onSurface.hex }}" },
    ["@keyword"] = { link = "Keyword" },
    ["@keyword.function"] = { fg = "#{{ primary.hex }}", italic = true },
    ["@keyword.operator"] = { link = "Operator" },
    ["@keyword.return"] = { fg = "#{{ primary.hex }}", bold = true },
    ["@conditional"] = { link = "Conditional" },
    ["@repeat"] = { link = "Repeat" },
    ["@debug"] = { link = "Debug" },
    ["@label"] = { link = "Label" },
    ["@include"] = { link = "Include" },
    ["@exception"] = { link = "Exception" },
    ["@type"] = { link = "Type" },
    ["@type.builtin"] = { fg = "#{{ tertiary.hex }}", italic = true },
    ["@storageclass"] = { link = "StorageClass" },
    ["@attribute"] = { fg = "#{{ yellow.hex }}" },
    ["@field"] = { fg = "#{{ teal.hex }}" },
    ["@property"] = { fg = "#{{ teal.hex }}" },
    ["@variable"] = { fg = "#{{ onSurface.hex }}" },
    ["@variable.builtin"] = { fg = "#{{ blue.hex }}", italic = true },
    ["@constant"] = { link = "Constant" },
    ["@constant.builtin"] = { fg = "#{{ mauve.hex }}", italic = true },
    ["@constant.macro"] = { link = "Macro" },
    ["@tag"] = { link = "Tag" },
    ["@tag.attribute"] = { fg = "#{{ teal.hex }}" },
    ["@tag.delimiter"] = { link = "Delimiter" },
    ["@text.title"] = { fg = "#{{ secondary.hex }}", bold = true },
    ["@text.uri"] = { fg = "#{{ blue.hex }}", underline = true },
    ["@text.reference"] = { fg = "#{{ mauve.hex }}", bold = true },
    ["@text.strong"] = { bold = true },
    ["@text.emphasis"] = { italic = true },

    -- 3. LSP Semantic Tokens
    ["@lsp.type.class"] = { link = "Type" },
    ["@lsp.type.enum"] = { link = "Type" },
    ["@lsp.type.interface"] = { link = "Type" },
    ["@lsp.type.struct"] = { link = "Type" },
    ["@lsp.type.typeParameter"] = { link = "Type" },
    ["@lsp.type.parameter"] = { link = "@parameter" },
    ["@lsp.type.variable"] = { link = "@variable" },
    ["@lsp.type.property"] = { link = "@property" },
    ["@lsp.type.enumMember"] = { link = "@constant" },
    ["@lsp.type.function"] = { link = "Function" },
    ["@lsp.type.method"] = { link = "@method" },
    ["@lsp.type.macro"] = { link = "Macro" },
    ["@lsp.type.decorator"] = { link = "PreProc" },

    -- 4. UI Elements (The "Polish")
    LineNr = { fg = "#{{ outline.hex }}" },
    CursorLineNr = { fg = "#{{ secondary.hex }}", bold = true },
    CursorLine = { bg = "#{{ surfaceContainerLow.hex }}" },
    CursorColumn = { bg = "#{{ surfaceContainerLow.hex }}" },
    VertSplit = { fg = "#{{ outlineVariant.hex }}" },
    WinSeparator = { fg = "#{{ outlineVariant.hex }}" },
    SignColumn = { bg = "NONE" },
    ColorColumn = { bg = "#{{ surfaceContainerLow.hex }}" },
    Folded = { fg = "#{{ onSurfaceVariant.hex }}", bg = "#{{ surfaceContainerLow.hex }}", italic = true },
    FoldColumn = { fg = "#{{ outline.hex }}", bg = "NONE" },
    
    Pmenu = { fg = "#{{ onSurface.hex }}", bg = "#{{ surfaceContainer.hex }}" },
    PmenuSel = { fg = "#{{ onPrimaryContainer.hex }}", bg = "#{{ primaryContainer.hex }}", bold = true },
    PmenuSbar = { bg = "#{{ surfaceContainerHigh.hex }}" },
    PmenuThumb = { bg = "#{{ outline.hex }}" },
    
    StatusLine = { fg = "#{{ onSurface.hex }}", bg = "#{{ surfaceContainerHigh.hex }}" },
    StatusLineNC = { fg = "#{{ onSurfaceVariant.hex }}", bg = "#{{ surfaceContainer.hex }}" },
    TabLine = { fg = "#{{ onSurfaceVariant.hex }}", bg = "#{{ surfaceContainer.hex }}" },
    TabLineFill = { bg = "#{{ surface.hex }}" },
    TabLineSel = { fg = "#{{ onPrimaryContainer.hex }}", bg = "#{{ primaryContainer.hex }}", bold = true },

    Visual = { bg = "#{{ secondaryContainer.hex }}" },
    Search = { fg = "#{{ onTertiaryContainer.hex }}", bg = "#{{ tertiaryContainer.hex }}" },
    IncSearch = { fg = "#{{ onPrimaryContainer.hex }}", bg = "#{{ primaryContainer.hex }}" },
    MatchParen = { fg = "#{{ primary.hex }}", underline = true, bold = true },
    
    Question = { fg = "#{{ sky.hex }}" },
    WildMenu = { fg = "#{{ onPrimaryContainer.hex }}", bg = "#{{ primaryContainer.hex }}" },
    Directory = { fg = "#{{ secondary.hex }}" },
    Title = { fg = "#{{ primary.hex }}", bold = true },

    -- 5. Diagnostics
    DiagnosticError = { fg = "#{{ error.hex }}" },
    DiagnosticWarn = { fg = "#{{ yellow.hex }}" },
    DiagnosticInfo = { fg = "#{{ blue.hex }}" },
    DiagnosticHint = { fg = "#{{ sky.hex }}" },
    DiagnosticUnderlineError = { sp = "#{{ error.hex }}", undercurl = true },
    DiagnosticUnderlineWarn = { sp = "#{{ yellow.hex }}", undercurl = true },
    DiagnosticUnderlineInfo = { sp = "#{{ blue.hex }}", undercurl = true },
    DiagnosticUnderlineHint = { sp = "#{{ sky.hex }}", undercurl = true },

    -- 6. Git
    diffAdded = { fg = "#{{ green.hex }}" },
    diffRemoved = { fg = "#{{ red.hex }}" },
    diffChanged = { fg = "#{{ blue.hex }}" },
    DiffAdd = { bg = "#{{ surfaceContainerLow.hex }}", fg = "#{{ green.hex }}" },
    DiffChange = { bg = "#{{ surfaceContainerLow.hex }}", fg = "#{{ blue.hex }}" },
    DiffDelete = { bg = "#{{ surfaceContainerLow.hex }}", fg = "#{{ red.hex }}" },
    DiffText = { bg = "#{{ tertiaryContainer.hex }}", fg = "#{{ onTertiaryContainer.hex }}" },

    -- 7. Plugin Specific
    TelescopeBorder = { fg = "#{{ outline.hex }}" },
    TelescopePromptBorder = { fg = "#{{ primary.hex }}" },
    TelescopeSelection = { bg = "#{{ surfaceContainerHigh.hex }}", bold = true },
    
    NeoTreeDirectoryIcon = { fg = "#{{ secondary.hex }}" },
    NeoTreeDirectoryName = { fg = "#{{ secondary.hex }}", bold = true },
    NeoTreeFileName = { fg = "#{{ onSurface.hex }}" },
    NeoTreeSymbolicLinkTarget = { fg = "#{{ sky.hex }}", italic = true },
    NeoTreeRootName = { fg = "#{{ primary.hex }}", bold = true },
  }
}
