return {
  mode = "{{ mode }}",
  palette = {
    bg0 = "#{{ surface.hex }}",
    bg1 = "#{{ surfaceContainerLow.hex }}",
    bg2 = "#{{ surfaceContainer.hex }}",
    bg3 = "#{{ surfaceContainerHigh.hex }}",
    bg4 = "#{{ surfaceContainerHighest.hex }}",
    fg0 = "#{{ onSurface.hex }}",
    fg1 = "#{{ onSurfaceVariant.hex }}",
    fg2 = "#{{ onSecondaryContainer.hex }}",
    fg3 = "#{{ outline.hex }}",
    fg4 = "#{{ outlineVariant.hex }}",
    red    = "#{{ error.hex }}",
    green  = "#{{ success.hex }}",
    yellow = "#{{ tertiary.hex }}",
    blue   = "#{{ primary.hex }}",
    purple = "#{{ secondary.hex }}",
    aqua   = "#{{ primaryFixed.hex }}",
    orange = "#{{ secondaryFixed.hex }}",
    faded_red    = "#{{ errorContainer.hex }}",
    faded_blue   = "#{{ primaryContainer.hex }}",
    faded_yellow = "#{{ tertiaryContainer.hex }}",
  }
}
