# Auto-generated by caelestia — do not edit directly
# Source: ~/.config/caelestia/templates/p10k-colors.zsh

# Directory — clear hierarchy: dim < neutral < accent+bold
typeset -g POWERLEVEL9K_DIR_SHORTENED_FOREGROUND='#{{ outline.hex }}'
typeset -g POWERLEVEL9K_DIR_FOREGROUND='#{{ onSurface.hex }}'
typeset -g POWERLEVEL9K_DIR_ANCHOR_FOREGROUND='#{{ primary.hex }}'

# VCS (git) — my_git_formatter reads these as prompt escapes (%F{hex})
# Fallbacks in my_git_formatter keep the original xterm values when caelestia isn't active.
typeset -g _CAELESTIA_VCS_CLEAN='%F{#{{ green.hex }}}'
typeset -g _CAELESTIA_VCS_MODIFIED='%F{#{{ peach.hex }}}'
typeset -g _CAELESTIA_VCS_UNTRACKED='%F{#{{ teal.hex }}}'
typeset -g _CAELESTIA_VCS_CONFLICTED='%F{#{{ error.hex }}}'

# Prompt char — vi mode × ok/error
typeset -g POWERLEVEL9K_PROMPT_CHAR_OK_VIINS_FOREGROUND='#{{ primary.hex }}'
typeset -g POWERLEVEL9K_PROMPT_CHAR_OK_VICMD_FOREGROUND='#{{ secondary.hex }}'
typeset -g POWERLEVEL9K_PROMPT_CHAR_OK_VIVIS_FOREGROUND='#{{ tertiary.hex }}'
typeset -g POWERLEVEL9K_PROMPT_CHAR_OK_VIOWR_FOREGROUND='#{{ tertiary.hex }}'
typeset -g POWERLEVEL9K_PROMPT_CHAR_ERROR_VIINS_FOREGROUND='#{{ error.hex }}'
typeset -g POWERLEVEL9K_PROMPT_CHAR_ERROR_VICMD_FOREGROUND='#{{ error.hex }}'
typeset -g POWERLEVEL9K_PROMPT_CHAR_ERROR_VIVIS_FOREGROUND='#{{ error.hex }}'
typeset -g POWERLEVEL9K_PROMPT_CHAR_ERROR_VIOWR_FOREGROUND='#{{ error.hex }}'

# Exit status
typeset -g POWERLEVEL9K_STATUS_OK_FOREGROUND='#{{ green.hex }}'
typeset -g POWERLEVEL9K_STATUS_OK_PIPE_FOREGROUND='#{{ green.hex }}'
typeset -g POWERLEVEL9K_STATUS_ERROR_FOREGROUND='#{{ error.hex }}'
typeset -g POWERLEVEL9K_STATUS_ERROR_SIGNAL_FOREGROUND='#{{ error.hex }}'
typeset -g POWERLEVEL9K_STATUS_ERROR_PIPE_FOREGROUND='#{{ error.hex }}'

# Right-prompt info segments
typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_FOREGROUND='#{{ outline.hex }}'
typeset -g POWERLEVEL9K_BACKGROUND_JOBS_FOREGROUND='#{{ tertiary.hex }}'
typeset -g POWERLEVEL9K_DIRENV_FOREGROUND='#{{ yellow.hex }}'
typeset -g POWERLEVEL9K_YAZI_FOREGROUND='#{{ peach.hex }}'

# Time
typeset -g POWERLEVEL9K_TIME_FOREGROUND='#{{ secondary.hex }}'

# Context (user@host) — only shown for remote/sudo sessions
typeset -g POWERLEVEL9K_CONTEXT_FOREGROUND='#{{ onSurfaceVariant.hex }}'
typeset -g POWERLEVEL9K_CONTEXT_ROOT_FOREGROUND='#{{ error.hex }}'
typeset -g POWERLEVEL9K_CONTEXT_{REMOTE,REMOTE_SUDO}_FOREGROUND='#{{ tertiary.hex }}'

# Ruler / gap line
typeset -g POWERLEVEL9K_RULER_FOREGROUND='#{{ outlineVariant.hex }}'
