# Keyring and auth
exec-once = gnome-keyring-daemon --start --components=secrets
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1

# Clipboard history
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store

# Auto delete trash 30 days old
exec-once = trash-empty 30

# Cursors
exec-once = hyprctl setcursor $cursorTheme $cursorSize
exec-once = gsettings set org.gnome.desktop.interface cursor-theme '$cursorTheme'
exec-once = gsettings set org.gnome.desktop.interface cursor-size $cursorSize

# Location provider and night light
exec-once = /usr/lib/geoclue-2.0/demos/agent
exec-once = sleep 1 && gammastep

# Forward bluetooth media commands to MPRIS
exec-once = mpris-proxy

# Resize and move windows based on matches (e.g. pip)
exec-once = caelestia resizer -d

# Start shell
exec-once = caelestia shell -d

# Fix dolphin MIME
exec-once = kbuildsycoca6 --noincremental

# exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = bat cache --build
exec-once = qs -c overview
exec-once = hyprpm reload

 # hypr-hints
# exec-once = dbus-update-activation-environment --systemd AT_SPI_BUS_ADDRESS=unix:path=/run/user/1000/at-spi/bus_1

# XEmbed-to-SNI bridge (for legacy tray icons like XDM)
exec-once = xembedsniproxy

# xdm (X11 backend needed for GtkStatusIcon → XEmbed → xembedsniproxy → SNI)
exec-once = sleep 2 && GDK_BACKEND=x11 /opt/xdman/xdm-app --background
