input {
    kb_layout = us
    numlock_by_default = false
    repeat_delay = 250
    repeat_rate = 35

    focus_on_close = 1

    touchpad {
        natural_scroll = true
        disable_while_typing = $touchpadDisableTyping
        scroll_factor = $touchpadScrollFactor
    }
}

device {
    name = 2.4g-receiver-mouse
    sensitivity = -0.5
}
device {
    name = elan1203:00-04f3:307a-touchpad
    sensitivity = 0.75
  }


binds {
    scroll_event_delay = 0
}

cursor {
    hotspot_padding = 1
    # no_hardware_cursors = true
}

