[custom]
accounts\storage-whats\css\disabled_files=@Variant(\0\0\0\t\0\0\0\x1\0\0\0\n\0\0\0\x14\0z\0\x61\0p\0z\0\x61\0p\0.\0\x63\0s\0s)
accounts\storage-whats\css\enabled=true
accounts\storage-whats\inherit=false
accounts\storage-whats\js\enabled=false
global\css\disabled_files=caelestia_1.css, default-slug.css, zapzap.css
global\css\enabled=true
global\js\enabled=false

[main]
geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\0\0\0\0\0\0\0\0\a\"\0\0\x4\r\0\0\0\0\0\0\0\0\0\0\a\"\0\0\x4\r\0\0\0\0\x2\0\0\0\a\x80\0\0\0\0\0\0\0\0\0\0\a\"\0\0\x4\r)
windowState=@ByteArray(\0\0\0\xff\0\0\0\0\xfd\0\0\0\0\0\0\a#\0\0\x3\xf5\0\0\0\x4\0\0\0\x4\0\0\0\b\0\0\0\b\xfc\0\0\0\0)

[notification]
donation_message=true

[system]
DontUseNativeDialog=false
sidebar=false
spellCheckers=true
theme=auto
tray_theme=symbolic_dark
wayland=true

[web]
scroll_animator=true

[website]
open_page=false
